# Generated by Django 4.0 on 2021-12-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(upload_to='pics')),
                ('header_phone', models.IntegerField()),
                ('footer_logo', models.ImageField(upload_to='pics')),
                ('footer_intro', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
                ('mobile1', models.IntegerField()),
                ('mobile2', models.IntegerField()),
                ('quotes1', models.TextField()),
                ('quotes2', models.TextField()),
            ],
        ),
    ]
