# Generated by Django 4.0 on 2021-12-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_workingprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingprocess',
            name='icon',
        ),
    ]
