# Generated by Django 3.2.9 on 2022-01-11 09:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_vision_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
