# Generated by Django 3.2.9 on 2022-01-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_vision_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='description',
            field=models.TextField(),
        ),
    ]
